Initial batch of pytests and CI testing (#665)
* Rudimentary pytests and CI updates to run tests

* Update poetry install command

* Add CI sound system setup

* Add error handling for API requests

* Disable fail-fast for CI workflows

* Refactor tests device refresh rate to use available FPS options - differs across CI runners

* Add LedFx test log artifact upload

* Add if condition for always() in upload-artifact step

* Remove version and smoketests from all CI and add Audio Input in linux CI workflows

* Refactor test runner and test utils

* Update upload-artifact action to v4 and change log file path

* Update debug log file path in CI workflows

* Ignore tests on linux, add -vv to pytest for better logging

* Update typing import in test_utils.py

* Reenable linux tests

* Update tests to minimise test runtime

* Cleanup test_utils

* Use a random port for testing and increase retries and backoff

* Refactor test setup and teardown

Add sleep after test case execution

* Add debug logging for API requests

* Add 50ms delay between requests - try to help with strange CI stuff

* Add a closing flag, which gets cleared if a new effect is applied. Addresses a clear_effect race condition exposed by pytest

* clean up and protect clear_all_effects

* move to handle.cancel() asyncio method

* Update pytest verbosity level in CI workflows and remove intel OS X tests

---------

Co-authored-by: atod <anthony.tod@gmail.com>

diff --git a/.github/workflows/ci-build-osx-arm.yml b/.github/workflows/ci-build-osx-arm.yml
--- a/.github/workflows/ci-build-osx-arm.yml
+++ b/.github/workflows/ci-build-osx-arm.yml
@@ -11,6 +11,7 @@ jobs:
     strategy:
       matrix:
         python: [3.10.x,3.11.x,3.12.x]
+      fail-fast: false
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v4
@@ -30,6 +31,9 @@ jobs:
       - name: Install poetry via Homebrew
         run: |
           brew install poetry
+      - name: Set poetry Python version
+        run: |
+          poetry env use python${{ matrix.python }}
       - name: Build LedFx wheel
         run: |
           poetry build
@@ -37,12 +41,18 @@ jobs:
         run: |
           export LDFLAGS="-L/opt/homebrew/opt/mbedtls@2/lib"
           export CPPFLAGS="-I/opt/homebrew/opt/mbedtls@2/include"
-          poetry install
-      - name: Smoketest LedFx
+          poetry install --with dev
+      - name: Test LedFx
         run: |
           source $(poetry env info -p)/bin/activate
-          ledfx --ci-smoke-test
+          pytest -v
           if [ $? -ne 0 ]; then
-            echo "LedFx launch failed: $?"
+            echo "LedFx tests failed: $?"
             exit 1
           fi
+      - name: Attach LedFx test log
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: ledfx-log-osx-arm-${{ matrix.python }}.log
+          path: ${{ github.workspace }}/debug_config/LedFx.log
