Add Smoketest to regular CI

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -32,6 +32,14 @@ jobs:
       - name: Install LedFx
         run: |
           poetry install
+      - name: Smoketest LedFx
+        run: |
+          source $(poetry env info -p)/bin/activate
+          ledfx --ci-smoke-test
+          if [ $? -ne 0 ]; then
+            echo "LedFx launch failed: $?"
+            exit 1
+          fi
 
   build-ledfx-windows:
     name: Build LedFx (Windows)
@@ -56,6 +64,14 @@ jobs:
       - name: Install LedFx
         run: |
           poetry install
+      - name: Smoketest LedFx
+        run: |
+          source $(poetry env info -p)/bin/activate
+          ledfx --ci-smoke-test
+          if [ $? -ne 0 ]; then
+            echo "LedFx launch failed: $?"
+            exit 1
+          fi      
 
   build-ledfx-osx:
     name: Build LedFx (OS X)
@@ -83,3 +99,11 @@ jobs:
       - name: Install LedFx
         run: |
           poetry install
+      - name: Smoketest LedFx
+        run: |
+          source $(poetry env info -p)/bin/activate
+          ledfx --ci-smoke-test
+          if [ $? -ne 0 ]; then
+            echo "LedFx launch failed: $?"
+            exit 1
+          fi
