One more time

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -71,7 +71,7 @@ jobs:
         run: echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH
 
       - name: Enable long paths for git on Windows
-      
+
         # Enable handling long path names (+260 char) on the Windows platform
         # https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
         run: git config --system core.longpaths true
@@ -96,18 +96,18 @@ jobs:
       - name: Smoketest LedFx with poetry
         run: |
           poetry run ledfx --ci-smoke-test
-          if ($LASTEXITCODE -ne 0) {
-            Write-Host "LedFx launch failed: $LASTEXITCODE"
+          if [ $? -ne 0 ]; then
+            echo "LedFx launch failed: $?"
             exit 1
-          }
+          fi
 
-      - name: Smoketest LedFx with poetry
+      - name: Smoketest LedFx
         run: |
-          poetry run ledfx --ci-smoke-test
-          if ($LASTEXITCODE -ne 0) {
-            Write-Host "LedFx launch failed: $LASTEXITCODE"
+          ledfx --ci-smoke-test
+          if [ $? -ne 0 ]; then
+            echo "LedFx launch failed: $?"
             exit 1
-          }   
+          fi   
 
   build-ledfx-osx:
     name: Build LedFx (OS X)
